# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    labels:
      - "theme/dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: /
    labels:
      - "theme/dependencies"
      - "theme/ci"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    groups:
      actions:
        patterns:
          - "*"
